"""baseline schema

Revision ID: 06e94753818a
Revises:
Create Date: 2026-07-14 15:22:42.995497

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06e94753818a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=True),
        sa.Column("bank_name", sa.String(length=50), nullable=False),
        sa.Column("account_number", sa.String(length=20), nullable=False),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("account_number"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("audit_log_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("success", "failure", name="audit_status"), nullable=False
        ),
        sa.Column("payload_snapshot", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("audit_log_id"),
    )
    op.create_table(
        "card_products",
        sa.Column("card_product_id", sa.String(length=36), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "외식",
                "쇼핑",
                "여행",
                "웹구독",
                "마트/편의점",
                name="card_product_category",
            ),
            nullable=False,
        ),
        sa.Column("annual_fee", sa.Integer(), nullable=False),
        sa.Column("benefits", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("card_product_id"),
    )
    op.create_table(
        "cards",
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("limit", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("card_id"),
    )
    op.create_index(op.f("ix_cards_account_id"), "cards", ["account_id"], unique=False)
    op.create_table(
        "daily_closing_snapshots",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("closing_balance", sa.BigInteger(), nullable=False),
        sa.Column("sum_credit", sa.BigInteger(), nullable=False),
        sa.Column("sum_debit", sa.BigInteger(), nullable=False),
        sa.Column("last_entry_rowid", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "business_date"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("sender_account_id", sa.String(length=36), nullable=False),
        sa.Column("receiver_account_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("success", "failure", name="transaction_status"),
            nullable=False,
        ),
        sa.Column("settlement_type", sa.String(length=32), nullable=True),
        sa.Column("settlement_card_id", sa.String(length=36), nullable=True),
        sa.Column("settlement_watermark_rowid", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["receiver_account_id"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_transactions_idempotency_key"),
        "transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transactions_settlement_card_id"),
        "transactions",
        ["settlement_card_id"],
        unique=False,
    )
    op.create_table(
        "card_ledger_entries",
        sa.Column("card_ledger_entry_id", sa.String(length=36), nullable=False),
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("merchant_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.card_id"],
        ),
        sa.PrimaryKeyConstraint("card_ledger_entry_id"),
    )
    op.create_index(
        op.f("ix_card_ledger_entries_card_id"),
        "card_ledger_entries",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_card_ledger_entries_idempotency_key"),
        "card_ledger_entries",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "ledger_entries",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column(
            "entry_type", sa.Enum("DEBIT", "CREDIT", name="entry_type"), nullable=False
        ),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("running_balance", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ledger_entries")
    op.drop_index(
        op.f("ix_card_ledger_entries_idempotency_key"), table_name="card_ledger_entries"
    )
    op.drop_index(
        op.f("ix_card_ledger_entries_card_id"), table_name="card_ledger_entries"
    )
    op.drop_table("card_ledger_entries")
    op.drop_index(op.f("ix_transactions_settlement_card_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("daily_closing_snapshots")
    op.drop_index(op.f("ix_cards_account_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_table("card_products")
    op.drop_table("audit_logs")
    op.drop_table("accounts")
    # ### end Alembic commands ###
