"""add category to card_ledger_entries

Revision ID: 8d934672ae0e
Revises: 06e94753818a
Create Date: 2026-07-20 15:27:00.810911

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d934672ae0e"
down_revision: Union[str, Sequence[str], None] = "06e94753818a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_ledger_entries",
        sa.Column("category", sa.String(length=30), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_ledger_entries", "category")
    # ### end Alembic commands ###
