"""create recipient_candidates

Revision ID: 2ea0ff81f9c5
Revises: a9373beee237
Create Date: 2026-07-17 18:23:53.639605

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ea0ff81f9c5"
down_revision: Union[str, Sequence[str], None] = "a9373beee237"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipient_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=False),
        sa.Column("recipient_account_id", sa.UUID(), nullable=False),
        sa.Column("resolved_name", sa.String(length=100), nullable=False),
        sa.Column("bank_name", sa.String(length=50), nullable=True),
        sa.Column("masked_account_number", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_session_id"],
            ["chat_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipient_candidates_chat_session_id"),
        "recipient_candidates",
        ["chat_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipient_candidates_user_id"),
        "recipient_candidates",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recipient_candidates_user_id"), table_name="recipient_candidates"
    )
    op.drop_index(
        op.f("ix_recipient_candidates_chat_session_id"),
        table_name="recipient_candidates",
    )
    op.drop_table("recipient_candidates")
    # ### end Alembic commands ###
