"""create pending_inputs

Revision ID: 317ff87f3f12
Revises: 2ea0ff81f9c5
Create Date: 2026-07-18 23:30:09.628990

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "317ff87f3f12"
down_revision: Union[str, Sequence[str], None] = "2ea0ff81f9c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_inputs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("input_request_id", sa.String(length=100), nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=False),
        sa.Column("execution_context_id", sa.UUID(), nullable=True),
        sa.Column("agent_thread_id", sa.String(length=100), nullable=True),
        sa.Column("ui_contract_id", sa.String(length=100), nullable=False),
        sa.Column("ui_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_session_id"],
            ["chat_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_context_id"],
            ["execution_contexts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pending_inputs_chat_session_id"),
        "pending_inputs",
        ["chat_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_inputs_execution_context_id"),
        "pending_inputs",
        ["execution_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_inputs_input_request_id"),
        "pending_inputs",
        ["input_request_id"],
        unique=False,
    )
    op.create_index(op.f("ix_pending_inputs_status"), "pending_inputs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_inputs_status"), table_name="pending_inputs")
    op.drop_index(op.f("ix_pending_inputs_input_request_id"), table_name="pending_inputs")
    op.drop_index(op.f("ix_pending_inputs_execution_context_id"), table_name="pending_inputs")
    op.drop_index(op.f("ix_pending_inputs_chat_session_id"), table_name="pending_inputs")
    op.drop_table("pending_inputs")
    # ### end Alembic commands ###
