"""create confirmation, idempotency, financial audit tables

Revision ID: 7d80f635a816
Revises: dbe684a809de
Create Date: 2026-07-16 18:33:56.954086

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d80f635a816"
down_revision: Union[str, Sequence[str], None] = "dbe684a809de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_context_id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", name="idempotency_status"),
            nullable=False,
        ),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_context_id",
            "operation",
            "idempotency_key",
            name="ux_idempotency_scope_key",
        ),
    )
    op.create_index(
        op.f("ix_idempotency_keys_execution_context_id"),
        "idempotency_keys",
        ["execution_context_id"],
        unique=False,
    )
    op.create_table(
        "financial_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("execution_context_id", sa.UUID(), nullable=True),
        sa.Column("chat_session_id", sa.UUID(), nullable=True),
        sa.Column("agent_thread_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("contract_id", sa.String(length=64), nullable=True),
        sa.Column("confirmation_id", sa.UUID(), nullable=True),
        sa.Column("auth_context_id", sa.UUID(), nullable=True),
        sa.Column("transaction_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column(
            "policy_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_audit_logs_confirmation_id"),
        "financial_audit_logs",
        ["confirmation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_audit_logs_event_type"),
        "financial_audit_logs",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_audit_logs_execution_context_id"),
        "financial_audit_logs",
        ["execution_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_audit_logs_occurred_at"),
        "financial_audit_logs",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_audit_logs_user_id"),
        "financial_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "confirmations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_context_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "DEFAULT_ACCOUNT_CHANGE",
                "ACCOUNT_ALIAS_CHANGE",
                "INTERNAL_TRANSFER",
                "EXTERNAL_TRANSFER",
                name="confirmation_operation",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "INVALIDATED",
                "CANCELLED",
                "EXECUTED",
                "EXPIRED",
                name="confirmation_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "fixed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_context_id"],
            ["execution_contexts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_confirmations_execution_context_id"),
        "confirmations",
        ["execution_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_confirmations_status"), "confirmations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_confirmations_user_id"), "confirmations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_confirmations_user_id"), table_name="confirmations")
    op.drop_index(op.f("ix_confirmations_status"), table_name="confirmations")
    op.drop_index(
        op.f("ix_confirmations_execution_context_id"), table_name="confirmations"
    )
    op.drop_table("confirmations")
    op.drop_index(
        op.f("ix_financial_audit_logs_user_id"), table_name="financial_audit_logs"
    )
    op.drop_index(
        op.f("ix_financial_audit_logs_occurred_at"), table_name="financial_audit_logs"
    )
    op.drop_index(
        op.f("ix_financial_audit_logs_execution_context_id"),
        table_name="financial_audit_logs",
    )
    op.drop_index(
        op.f("ix_financial_audit_logs_event_type"), table_name="financial_audit_logs"
    )
    op.drop_index(
        op.f("ix_financial_audit_logs_confirmation_id"),
        table_name="financial_audit_logs",
    )
    op.drop_table("financial_audit_logs")
    op.drop_index(
        op.f("ix_idempotency_keys_execution_context_id"), table_name="idempotency_keys"
    )
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
