"""add new column to account table

Revision ID: 8dd361bcc2ad
Revises: edf3288029e1
Create Date: 2026-07-10 15:06:25.989439

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dd361bcc2ad"
down_revision: Union[str, Sequence[str], None] = "edf3288029e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("external_account_id", sa.String(length=64), nullable=True),
    )
    op.create_unique_constraint(None, "accounts", ["external_account_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="unique")  # type: ignore
    op.drop_column("accounts", "external_account_id")
    # ### end Alembic commands ###
