"""create auth_contexts

Revision ID: a9373beee237
Revises: 7d80f635a816
Create Date: 2026-07-17 16:17:45.495118

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a9373beee237"
down_revision: Union[str, Sequence[str], None] = "7d80f635a816"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("confirmation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "FAILED",
                "CANCELLED",
                "EXPIRED",
                name="auth_context_status",
            ),
            nullable=False,
        ),
        sa.Column("available_methods", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["confirmation_id"],
            ["confirmations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_contexts_confirmation_id"),
        "auth_contexts",
        ["confirmation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_auth_contexts_status"), "auth_contexts", ["status"], unique=False)
    op.create_index(op.f("ix_auth_contexts_user_id"), "auth_contexts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_contexts_user_id"), table_name="auth_contexts")
    op.drop_index(op.f("ix_auth_contexts_status"), table_name="auth_contexts")
    op.drop_index(op.f("ix_auth_contexts_confirmation_id"), table_name="auth_contexts")
    op.drop_table("auth_contexts")
    # ### end Alembic commands ###
