"""create transaction_query_contexts

Revision ID: dbe684a809de
Revises: b2c3d4e5f6a7
Create Date: 2026-07-15 20:40:39.327021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbe684a809de"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_query_contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "account_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("keyword", sa.String(length=100), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=True),
        sa.Column("page_size", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_query_contexts_user_id"),
        "transaction_query_contexts",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ux_accounts_user_default"),
        table_name="accounts",
        postgresql_where="is_default",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ux_accounts_user_default"),
        "accounts",
        ["user_id"],
        unique=True,
        postgresql_where="is_default",
    )
    op.drop_index(
        op.f("ix_transaction_query_contexts_user_id"),
        table_name="transaction_query_contexts",
    )
    op.drop_table("transaction_query_contexts")
    # ### end Alembic commands ###
